.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH fnm-help 1  "help " 
.SH NAME
fnm\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBfnm help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
fnm\-help\-list\-remote(1)
List all remote Node.js versions
.TP
fnm\-help\-list(1)
List all locally installed Node.js versions
.TP
fnm\-help\-install(1)
Install a new Node.js version
.TP
fnm\-help\-use(1)
Change Node.js version
.TP
fnm\-help\-env(1)
Print and set up required environment variables for fnm
.TP
fnm\-help\-completions(1)
Print shell completions to stdout
.TP
fnm\-help\-alias(1)
Alias a version to a common name
.TP
fnm\-help\-unalias(1)
Remove an alias definition
.TP
fnm\-help\-default(1)
Set a version as the default version or get the current default version
.TP
fnm\-help\-current(1)
Print the current Node.js version
.TP
fnm\-help\-exec(1)
Run a command within fnm context
.TP
fnm\-help\-uninstall(1)
Uninstall a Node.js version
.TP
fnm\-help\-help(1)
Print this message or the help of the given subcommand(s)