#!/bin/bash

GIT_ROOT=$(git rev-parse --show-toplevel)

if [ "$GIT_ROOT" == "" ]; then
  echo "Git root cannot be empty"
  exit 1
fi

rm -f $GIT_ROOT/.git/hooks/pre-commit &> /dev/null
ln -s $GIT_ROOT/.ci/pre-commit-hook $GIT_ROOT/.git/hooks/pre-commit
