name: Documentation
on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  ensure_commands_markdown_is_correct:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest Node
        run: |
          curl -fsSL https://fnm.vercel.app/install | bash
          sudo install ~/.fnm/fnm /usr/bin/
          fnm install
      - name: Install Node deps
        run: fnm exec -- yarn
      - name: Generate command markdown
        run: |
          fnm exec -- yarn generate-command-docs --check
